### ISSUE TITLE
Base adress not found

### ISSUE THREAD

**Issue by Synclet** [jpmac26/M64MM2#10]
Whenever i start the programm, i see 3 diffrent statuses. The first one is: Projekt 64 isn´t open. The second one is: Proekt 64 is not open. And the last one is: Base adress not found. but my projekt 64 was open and i just tried to use the programm, because i still saw all buttons, but just as i expected, it didn´t work. 
Hope for a fast answer and fix.

-Synclet

**Comment by GlitchyPSIX** [comment]
Make sure your PJ64 is at least ver. 1.6, and that there's only *one* instance of PJ64.

**Comment by Synclet** [comment]
Just that everyone knows, the problem was a brocken game file. I just had to search for another M64 file to make it work. So if anyone who is reading this has the same problem, try another download for the game file.
