### ISSUE TITLE
Freeze Camera

### ISSUE THREAD

**Issue by cgraphicz** [jpmac26/M64MM2#2]
When I click Freeze Camera, it zooms way out. This also happens with Precision Control, although soft-freezing it does not do this.

**Comment by GlitchyPSIX** [comment]
That happens when you're in Castle Grounds?

**Comment by GlitchyPSIX** [comment]
Try changing camera type twice.

**Comment by CaptainSwag101** [comment]
This is because you have not changed the camera type before moving into an area outside of the castle. Before you leave the castle, make sure you click "Change Camera Type", then leave the castle, then click either "Unfreeze Camera" or "Go to new area", and the camera should be properly configured.
